baseURL = "https://nathancraddock.com/"
languageCode = "en-us"
title = "Nathan Craddock"

[author]
  name = "Nathan Craddock"

[taxonomies]
  tag = "tags"
  series = "series"

[markup]
  [markup.highlight]
    style = "friendly"

[outputFormats]
  [outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "feed"

# prevent new readers from getting a backlog of everything
rssLimit = 10
