baseURL = "http://nathancraddock.net"
languageCode = "en-us"
title = "Nathan Craddock"

[markup]
    [markup.highlight]
        codeFences = true
        lineNos = true
        tabWidth = 2
        style = "pygments"
